import type { UiDocument } from '../protocol';

/**
 * Fake multi-section document exercising every SchemaNode type.
 * Uses example.test / fake names only — no real hosts, handles, or user paths.
 */
export function createMockDocument(): UiDocument {
  return {
    title: 'FluentConfig Dev Preview',
    version: '0.1.0-dev',
    colorScheme: 'dark',
    sections: [
      {
        id: 'General',
        title: 'General',
        children: [
          {
            type: 'description',
            text: 'Standalone mock bridge — every control type below. Save and RPCs stay in-browser.',
          },
          {
            type: 'update-notice',
            id: 'self-update',
            currentVersion: '0.1.0-dev',
            latestVersion: '0.2.0',
            releaseNotes: 'Mock release notes: polish and bug fixes.',
            downloadUrl: 'https://example.test/releases/download/v0.2.0/Extension.dll',
            repo: 'example-org/example-extension',
            dismissible: true,
          },
          {
            type: 'title',
            text: 'Basics',
          },
          {
            type: 'toggle',
            id: 'feature_enabled',
            label: 'Enable feature',
            saveKey: 'feature_enabled',
            hint: 'Master switch for the sample feature.',
            defaultValue: true,
          },
          {
            type: 'textbox',
            label: 'Display name',
            saveKey: 'display_name',
            hint: 'Shown in notifications.',
            defaultValue: 'Demo Stream',
          },
          {
            type: 'textbox',
            label: 'API token',
            saveKey: 'api_token',
            hint: 'Password-style field (fake value only).',
            password: true,
            defaultValue: 'demo-token',
          },
          {
            type: 'textbox',
            label: 'Notes',
            saveKey: 'notes',
            multiline: true,
            defaultValue: 'Multiline notes for the mock form.',
          },
          { type: 'separator' },
          {
            type: 'toggle',
            label: 'Enable optional limit',
            saveKey: 'optional_limit_enabled',
            hint: 'Gates the slider below via ShowWhen.',
            defaultValue: false,
          },
          {
            type: 'slider',
            label: 'Optional limit',
            saveKey: 'optional_limit',
            min: 0,
            max: 100,
            defaultValue: 50,
            visibility: { saveKey: 'optional_limit_enabled', equals: true },
          },
          {
            type: 'group',
            id: 'inverted_group',
            visibility: {
              saveKey: 'feature_enabled',
              equals: true,
              inverted: true,
            },
            children: [
              {
                type: 'description',
                text: 'Visible only when “Enable feature” is off (inverted WithVisibility).',
              },
              {
                type: 'textbox',
                label: 'Fallback message',
                saveKey: 'fallback_message',
                defaultValue: 'Feature is disabled.',
              },
            ],
          },
        ],
      },
      {
        id: 'Inputs',
        title: 'Inputs',
        children: [
          {
            type: 'number-input',
            label: 'Rate',
            saveKey: 'rate_value',
            valueType: 'double',
            min: 0.1,
            max: 10,
            step: 0.1,
            defaultValue: 1,
            stepper: true,
          },
          {
            type: 'number-input',
            label: 'Retry count',
            saveKey: 'retry_count',
            valueType: 'int',
            min: 0,
            max: 20,
            step: 1,
            defaultValue: 3,
            stepper: true,
          },
          {
            type: 'slider',
            label: 'Volume',
            saveKey: 'volume',
            min: 0,
            max: 100,
            defaultValue: 75,
          },
          {
            type: 'color-picker',
            label: 'Accent color',
            saveKey: 'accent_color',
            defaultValue: '#3b82f6',
          },
          {
            type: 'duration-input',
            label: 'Cooldown',
            saveKey: 'cooldown',
            defaultValue: '30seconds',
            permanentOption: true,
          },
          {
            type: 'filepath',
            label: 'Export path',
            saveKey: 'export_filepath',
            hint: 'Browse is mocked — picks a fake path.',
            defaultValue: '',
          },
          {
            type: 'dropdown',
            id: 'channel_reward',
            label: 'Channel reward',
            saveKey: 'reward_display',
            valueSaveKey: 'reward_id',
            refreshable: true,
            defaultByValue: 'reward-2',
            options: [
              { value: 'reward-1', display: 'Highlight Message' },
              { value: 'reward-2', display: 'Hydrate Reminder' },
              { value: 'reward-3', display: 'Song Request' },
            ],
          },
          {
            type: 'dropdown',
            label: 'Simple choice',
            saveKey: 'simple_choice',
            options: [
              { value: 'Option A', display: 'Option A' },
              { value: 'Option B', display: 'Option B' },
              { value: 'Option C', display: 'Option C' },
            ],
            defaultIndex: 0,
          },
          {
            type: 'toggle',
            label: 'Exclusive modes',
            saveKey: 'exclusive_modes',
            hint: 'Multi-select exclusive toggles (max 2).',
            exclusive: {
              options: ['Quiet', 'Party', 'Focus', 'AFK'],
              maxSelected: 2,
              defaultIndices: [0],
            },
          },
          {
            type: 'button',
            id: 'btn-progress',
            text: 'Run progress demo',
            hint: 'Triggers a fake host progress sequence.',
            color: '#2563eb',
          },
          {
            type: 'button',
            id: 'btn-toast',
            text: 'Show toast',
            color: '#059669',
          },
        ],
      },
      {
        id: 'Lists',
        title: 'Lists',
        children: [
          {
            type: 'dynamic-textboxes',
            label: 'Allowed users',
            saveKey: 'allowed_users',
            hint: 'Add/remove string entries.',
            preset: ['viewer_one', 'viewer_two'],
            allowDuplicates: false,
          },
          {
            type: 'pill-input',
            id: 'test_items',
            label: 'Test items',
            saveKey: 'test_items',
            hint: 'Pills with nested schema children (no Panel leak).',
            itemTemplate: [
              { type: 'title', text: 'Item: {name}' },
              {
                type: 'toggle',
                label: 'Enabled',
                saveKey: '{name}_enabled',
                defaultValue: true,
              },
              {
                type: 'slider',
                label: 'Value',
                saveKey: '{name}_value',
                min: 0,
                max: 100,
                defaultValue: 50,
              },
            ],
            items: [
              {
                name: 'Alpha',
                children: [
                  { type: 'title', text: 'Item: Alpha' },
                  {
                    type: 'toggle',
                    label: 'Enabled',
                    saveKey: 'Alpha_enabled',
                    defaultValue: true,
                  },
                  {
                    type: 'slider',
                    label: 'Value',
                    saveKey: 'Alpha_value',
                    min: 0,
                    max: 100,
                    defaultValue: 50,
                  },
                ],
              },
              {
                name: 'Beta',
                children: [
                  { type: 'title', text: 'Item: Beta' },
                  {
                    type: 'toggle',
                    label: 'Enabled',
                    saveKey: 'Beta_enabled',
                    defaultValue: false,
                  },
                  {
                    type: 'slider',
                    label: 'Value',
                    saveKey: 'Beta_value',
                    min: 0,
                    max: 100,
                    defaultValue: 25,
                  },
                ],
              },
            ],
          },
          {
            type: 'repeatable-rows',
            id: 'command_rows',
            saveKey: 'command_rows',
            rowSchema: [
              {
                type: 'textbox',
                label: 'Command',
                saveKey: 'command',
                defaultValue: '',
              },
              {
                type: 'textbox',
                label: 'Reply',
                saveKey: 'reply',
                defaultValue: '',
              },
              {
                type: 'toggle',
                label: 'Enabled',
                saveKey: 'enabled',
                defaultValue: true,
              },
            ],
          },
        ],
      },
    ],
    values: {
      feature_enabled: true,
      display_name: 'Demo Stream',
      api_token: 'demo-token',
      notes: 'Multiline notes for the mock form.',
      optional_limit_enabled: false,
      optional_limit: 50,
      fallback_message: 'Feature is disabled.',
      rate_value: 1,
      retry_count: 3,
      volume: 75,
      accent_color: '#3b82f6',
      cooldown: '30seconds',
      export_filepath: '',
      reward_display: 'Hydrate Reminder',
      reward_id: 'reward-2',
      simple_choice: 'Option A',
      exclusive_modes: [0],
      allowed_users: ['viewer_one', 'viewer_two'],
      test_items: ['Alpha', 'Beta'],
      Alpha_enabled: true,
      Alpha_value: 50,
      Beta_enabled: false,
      Beta_value: 25,
      command_rows: [
        { command: '!hello', reply: 'Hi there', enabled: true },
        { command: '!discord', reply: 'Join the community', enabled: true },
      ],
    },
  };
}
