<#
.SYNOPSIS
  Reads the Vite single-file dist/index.html and emits EmbeddedHtml.Bundle.g.cs
  with the HTML as a verbatim string literal assigned in a static constructor helper.
#>
param(
    [Parameter(Mandatory = $true)][string]$HtmlPath,
    [Parameter(Mandatory = $true)][string]$OutPath
)

$ErrorActionPreference = 'Stop'
if (-not (Test-Path $HtmlPath)) {
    throw "Web bundle HTML not found: $HtmlPath"
}

$html = [System.IO.File]::ReadAllText($HtmlPath)
# Escape for C# verbatim string: double all quotes
$escaped = $html.Replace('"', '""')

$dir = Split-Path -Parent $OutPath
if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

$cs = @"
// <auto-generated />
// Vite single-file bundle embedded at build time. Do not edit.
namespace FluentConfig
{
    public static partial class EmbeddedHtml
    {
        static partial void LoadEmbeddedBundle(ref string content)
        {
            content = @"$escaped";
        }
    }
}
"@

[System.IO.File]::WriteAllText($OutPath, $cs, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote embedded HTML source ($([math]::Round($html.Length/1024.0, 1)) KB) -> $OutPath"
